### ISSUE TITLE
Transactions fail with "Tx with safe_tx_hash already exists in DB"

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/safe-relay-service#32]
We're experiencing multiple failing transactions through the relayer returning `Tx with safe_tx_hash=0x... already exists in DB` errors when calling POST `/api/v1/:safeAddress/transaction`.

**What we know so far using a "broken" Safe:**

* The Safe `0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e` currently has a Safe nonce `2`: https://xdai.gnosis-safe.io/app/#/safes/0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e/transactions
* The request to the relayer was issued for a transaction with safe nonce `3`, the above mentioned error (`exception"SafeMultisigTxExists: Tx with safe-nonce=3 for safe=0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e already exists in DB"`) was returned
* The request contained the following data:

```
{
  "to": "0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337",
  "value": 0,
  "data": "0xa2e62045",
  "operation": 0,
  "signatures": [
    {
      "r": "13848951216129082816644859483985406530918017491958550854288717089052663791938",
      "s": "11409471923590110953741147711128296886004416620036517910324853730435531504815",
      "v": 28
    }
  ],
  "safeTxGas": "90011",
  "dataGas": "48160",
  "gasPrice": "1",
  "nonce": "3",
  "gasToken": "0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337"
}
```

* In the database we can see the following in the `safe_multisigtx` table for this particular Safe:

```
-[ RECORD 1 ]---+-------------------------------------------------------------------------------------------------------------------------------------
id              | 1075873
created         | 2021-02-04 10:58:19.495583+00
modified        | 2021-02-04 10:58:19.495583+00
to              | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
value           | 0
data            | \xa2e62045
operation       | 0
safe_tx_gas     | 90011
data_gas        | 48160
gas_price       | 1
gas_token       | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
signatures      | \x1e9e3a865079ec110227d21e7979dc75b83eec9b1a422feaf0100fa98098c1421939884259cb54ed98efe9df3b46379644cf1853e484d118f8a88355cc1b7caf1c
nonce           | 3
safe_id         | 0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
refund_receiver |
safe_tx_hash    | fce50b8dc659efac9a970a968995f21d48a866ed5701c8af8ebaa5bcfe084bbd
ethereum_tx_id  | b21fd6838f34c6d28b4df21861c02af04a6d08f331965fab0d875ea1b98d920d
-[ RECORD 2 ]---+-------------------------------------------------------------------------------------------------------------------------------------
id              | 747220
created         | 2021-01-04 08:39:34.290225+00
modified        | 2021-01-04 08:39:34.290225+00
to              | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
value           | 0
data            | \xa2e62045
operation       | 0
safe_tx_gas     | 90011
data_gas        | 48160
gas_price       | 1
gas_token       | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
signatures      | \x10ef131cf74eb684d00410fa2b78b0a05e89b7e61554af8faced8afb661130426fc2ce507c7cea93a3eaec87fed066a2ad370c436466952cf86fa93bc9eb6cca1b
nonce           | 2
safe_id         | 0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
refund_receiver |
safe_tx_hash    | 329388d9a6678acf63914d47fd82548d11ee4c63aa003225dad71b8047f0eafb
ethereum_tx_id  | 1a8aefa7ae54201e2715b33da29fed8f459344c14195d89ba21eb056e57a7466
-[ RECORD 3 ]---+-------------------------------------------------------------------------------------------------------------------------------------
id              | 684958
created         | 2020-12-14 08:14:10.112406+00
modified        | 2020-12-14 08:14:10.112406+00
to              | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
value           | 0
data            | \xa2e62045
operation       | 0
safe_tx_gas     | 90011
data_gas        | 48160
gas_price       | 1
gas_token       | 0x5Bdb17A485FBD83727D802F8aaE05434a4C1e337
signatures      | \x9bbd91972a43ba827908a77a87a8d7382fd2bbcfd2dd3442f47f125a3f4374dc6f11ca1b683a47d082c801e0eba5de86b5040b27b01efc7c73b953e77e86e96f1c
nonce           | 1
safe_id         | 0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
refund_receiver |
safe_tx_hash    | 4df14f61310ea3f8e6e908e60df14207fb11cc48d8adb25c4fb4fdb6890d0f26
ethereum_tx_id  | a1dfce48fcb7c2df03c7da7763e4b21ffc7dda225ec28a2f2ec4ae217783efab
-[ RECORD 4 ]---+-------------------------------------------------------------------------------------------------------------------------------------
id              | 669683
created         | 2020-12-10 10:33:36.83506+00
modified        | 2020-12-10 10:33:36.83506+00
to              | 0x29b9a7fBb8995b2423a71cC17cf9810798F6C543
value           | 0
data            | \xb7bc0f73
operation       | 0
safe_tx_gas     | 1243433
data_gas        | 62920
gas_price       | 1000000000
gas_token       |
signatures      | \xca6126c6dfef4c7d0ec12869ff6d3c1069d43e87ea08377a4aa9b4c9f7a992fd3cd9a5b65265f7413c3c203090393eb3d06407836b33f7e3bd48d0a215f6ecc61c
nonce           | 0
safe_id         | 0x3cb406Def33aeD0ABD6D02a75FEdCa8e2E8D1A2e
refund_receiver |
safe_tx_hash    | c0971eaa7566f70f59d92527c9f14be8f035d56a82080682bf242a621d6a64f6
ethereum_tx_id  | 667324b7643dc0ad801ced9dc4e2fbabc7be64047712f0f57183e741d6667133
```

`RECORD 1` indicates that there is a request with nonce `3`. The attached ethereum tx id `b21fd6838f34c6d28b4df21861c02af04a6d08f331965fab0d875ea1b98d920d` seems to be unknown: https://blockscout.com/poa/xdai/search?q=b21fd6838f34c6d28b4df21861c02af04a6d08f331965fab0d875ea1b98d920d.

This database row has the same timestamp as the request made in the client wallet.

* The strange thing here: There is only one place where `SafeMultisigTx` entries get created in the database https://github.com/gnosis/safe-relay-service/blob/387c5de71a4c7d7171d366d4752fa0ca12552051/safe_relay_service/relay/services/transaction_service.py#L339 but this should happen when the actual request took place. Why was there already an entry?
* We assume that something is going wrong with updating / syncing up with the blockchain. Why does the entry contain an invalid `ethereum_tx_id`? We looked into the `check_and_update_pending_transactions` task https://github.com/gnosis/safe-relay-service/blob/master/safe_relay_service/relay/tasks.py#L397 and found the following in the logs. For some reason the task itself crashes with an `SoftTimeLimitExceeded` error. Is there too much to process for that task?

```
2021-02-04 11:26:14,649 [INFO] [MainProcess] Received task: safe_relay_service.relay.tasks.check_and_update_pending_transactions[7745520a-51bb-49d8-b44a-0e24370e1aeb]
2021-02-04 11:26:14,649 [INFO] [MainProcess] Received task: safe_relay_service.relay.tasks.check_and_update_pending_transactions[7745520a-51bb-49d8-b44a-0e24370e1aeb]
2021-02-04 11:27:14,651 [WARNING] [MainProcess] Soft time limit (60s) exceeded for safe_relay_service.relay.tasks.check_and_update_pending_transactions[7745520a-51bb-49d8-b44a-0e24370e1aeb]
2021-02-04 11:27:14,655 [ERROR] [ForkPoolWorker-4] Task safe_relay_service.relay.tasks.check_and_update_pending_transactions[7745520a-51bb-49d8-b44a-0e24370e1aeb] raised unexpected: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/safe-relay-service/safe_relay_service/relay/tasks.py", line 409, in check_and_update_pending_transactions
    ethereum_tx = transaction_service.create_or_update_ethereum_tx(multisig_tx.ethereum_tx_id)
  File "/safe-relay-service/safe_relay_
...
```

**Comment by adzialocha** [comment]
Related: https://github.com/CirclesUBI/safe-relay-service/issues/33

**Comment by adzialocha** [comment]
This problem occurred from an reorg on xDai, a higher waiting time should prevent this from happening in the future, see fix: https://github.com/CirclesUBI/safe-relay-service/pull/36
