### ISSUE TITLE
Raise soft-time limit for `check_and_update_pending_transactions`

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/safe-relay-service#34]
`check_and_update_pending_transactions` tasks seem to run longer than 60 seconds which is the current soft time limit:

```
2021-02-05 19:24:54,479 [INFO] [ForkPoolWorker-2] Task safe_relay_service.relay.tasks.check_and_update_pending_transactions[49053820-9f58-447d-a7b8-7beb49fb8f90] succeeded in 60.14815763942897s: 0
```

This leads sometimes to these exceptions which can be propably fixed if we just increase the limit:

```
2021-02-05 19:25:54,427 [ERROR] [ForkPoolWorker-4] Task safe_relay_service.relay.tasks.check_and_update_pending_transactions[14d695a6-8fb3-4f07-8a73-7a79b035fdf1] raised unexpected: SoftTimeLimitExceeded()
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/safe-relay-service/safe_relay_service/relay/tasks.py", line 409, in check_and_update_pending_transactions
    ethereum_tx = transaction_service.create_or_update_ethereum_tx(multisig_tx.ethereum_tx_id)
  File "/safe-relay-service/safe_relay_service/relay/services/transaction_service.py", line 581, in create_or_update_ethereum_tx
    tx_receipt = self.ethereum_client.get_transaction_receipt(tx_hash)
  File "/usr/local/lib/python3.8/site-packages/gnosis/eth/ethereum_client.py", line 1073, in get_transaction_receipt
    tx_receipt = self.w3.eth.getTransactionReceipt(tx_hash)
  File "/usr/local/lib/python3.8/site-packages/web3/module.py", line 44, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 154, in request_blocking
    response = self._make_request(method, params)
  File "/usr/local/lib/python3.8/site-packages/web3/manager.py", line 133, in _make_request
    return request_func(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
  File "/usr/local/lib/python3.8/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
    return make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
    response = make_request(method, formatted_params)
  File "/usr/local/lib/python3.8/site-packages/web3/middleware/attrdict.py", line 33, in middleware
    response = make_request(method, params)
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "/usr/local/lib/python3.8/site-packages/web3/middleware/formatting.py", line 76, in apply_formatters
    response = make_request(method, params)
```

**Comment by adzialocha** [comment]
This issue only occurs when invalid data is present in the database (see https://github.com/CirclesUBI/safe-relay-service/issues/32).
