### ISSUE TITLE
`AttributeError: 'str' object has no attribute 'get'` when sending to Organization

### ISSUE THREAD

**Issue by adzialocha** [CirclesUBI/safe-relay-service#43]
**Describe the bug**

Sending a transitive transaction from account `0x42cEDde51198D1773590311E2A340DC06B24cB37` to `0x783110347c923b8694EF90D01D70E8f2a62b3720` fails with this error on production:

```
2021-04-07 14:41:52,880
[WARNING] [MainProcess]
https://relay.circles.garden/api/v1/safes/0x42cEDde51198D1773590311E2A340DC06B24cB37/transactions/
Exception: AttributeError: 'str' object has no attribute 'get'
```

Data received:

```json
{
  "to": "0x29b9a7fBb8995b2423a71cC17cf9810798F6C543",
  "value": 0,
  "data": "0xd62fd9a200000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000140000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c0000000000000000000000000000000000000000000000000000000000000000500000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000057928fb15ffb7303b65edc326dc4dc38150008e10000000000000000000000003cb406def33aed0abd6d02a75fedca8e2e8d1a2e0000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000003cb406def33aed0abd6d02a75fedca8e2e8d1a2e000000000000000000000000000000000000000000000000000000000000000500000000000000000000000042cedde51198d1773590311e2a340dc06b24cb3700000000000000000000000042cedde51198d1773590311e2a340dc06b24cb370000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca1960000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000003cb406def33aed0abd6d02a75fedca8e2e8d1a2e00000000000000000000000000000000000000000000000000000000000000050000000000000000000000009a0bbbbd3789f184ca88f2f6a40f42406cb842ac0000000000000000000000007b2e78d4dfaaba045a167a70da285e30e8fca196000000000000000000000000783110347c923b8694ef90d01d70e8f2a62b37200000000000000000000000003cb406def33aed0abd6d02a75fedca8e2e8d1a2e000000000000000000000000783110347c923b8694ef90d01d70e8f2a62b3720000000000000000000000000000000000000000000000000000000000000000500000000000000000000000000000000000000000000000000000000000967b10000000000000000000000000000000000000000000000000de0b6b3a75a984f0000000000000000000000000000000000000000000000000de0b6b3a75a984f00000000000000000000000000000000000000000000000000000000000967b100000000000000000000000000000000000000000000000000000000000967b1",
  "operation": 0,
  "signatures": [
    {
      "r": "57259657708280990088562768952820609116102511735686444822895016186024652000797",
      "s": "15657059498934558017619829852586148878527354197756004816655274045090227541715",
      "v": 27
    }
  ],
  "safe_tx_gas": "673594",
  "data_gas": "55752",
  "gas_price": "1",
  "nonce": "255",
  "gas_token": "0xA41eDDD695443519A6C40F83d5c3D575E5C493A2",
  "safe": "0x42cEDde51198D1773590311E2A340DC06B24cB37"
}
```

**To Reproduce**
1. Send Circles to `0x783110347c923b8694EF90D01D70E8f2a62b3720` (Organization)

**Comment by adzialocha** [comment]
Maybe related:

```
'utf-8' codec can't decode byte 0xd2 in position 30: invalid continuation byte
Traceback (most recent call last):
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 436, in estimate_tx_gas_with_safe
    result: HexBytes = self.w3.eth.call(tx, block_identifier=block_identifier)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/module.py", line 58, in caller
    result = w3.manager.request_blocking(method_str, params, error_formatters)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 157, in request_blocking
    apply_error_formatters(error_formatters, response)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/manager.py", line 62, in apply_error_formatters
    formatted_response = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/web3/_utils/method_formatters.py", line 518, in raise_solidity_error_on_revert
    raise ContractLogicError(f'execution reverted: {bytes.fromhex(reason).decode("utf8")}')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 30: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    result = safe.estimate_tx_gas('0x333d72F54CF17BA7A1971e7C7E9acB91C8B709d2', 0, '0xa2e62045', 0)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 522, in estimate_tx_gas
    return self.estimate_tx_gas_by_trying(to, value, data, operation) + PROXY_GAS + OLD_CALL_GAS
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 491, in estimate_tx_gas_by_trying
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)
  File "/home/adz/.pyenv/versions/safe-estimate-issue/lib/python3.8/site-packages/gnosis/safe/safe.py", line 449, in estimate_tx_gas_with_safe
    data_dict = error_dict.get('data')
AttributeError: 'str' object has no attribute 'get'
```

**Comment by adzialocha** [comment]
Also maybe related: https://github.com/CirclesUBI/circles-api/issues/73
