### ISSUE TITLE
Fee too low error in latest relayer version

### ISSUE THREAD

**Issue by JacqueGM** [CirclesUBI/safe-relay-service#63]
Issue with  version[ v4.1.15-pre-2cc3ee6](https://github.com/CirclesUBI/safe-relay-service/tree/v4.1.15-pre-2cc3ee6) of relayer in STG might be related to 

https://github.com/cardstack/cardstack/pull/3234
https://github.com/portis-project/web-sdk/issues/142

![Screenshot 2022-11-04 at 16 47 16](https://user-images.githubusercontent.com/55389166/200018380-6c23a339-648b-4977-a8e2-937a05c0fa8e.png)

**Comment by JacqueGM** [comment]
This issue has also been seen in Production with relayer version `v4.1.15-pre-17848a3`
<img width="759" alt="Screenshot 2022-11-21 at 18 09 18" src="https://user-images.githubusercontent.com/55389166/203117808-7e6b7086-b98a-4ffa-a164-ab2979b0384c.png">

**Comment by JacqueGM** [comment]
the error seems to come from the EIP1559 support https://github.com/safe-global/safe-eth-py/blob/v4.5.1/gnosis/safe/safe_tx.py#L375

**Comment by llunaCreixent** [comment]
Also present in relayer `v5.0.2`: 
```
ValueError: {'code': -32010, 'message': 'FeeTooLow, EffectivePriorityFeePerGas too low 0 < 1, BaseFee: 7'}
```

**Comment by JacqueGM** [comment]
The main reason on this issue is the GasPrice is lowe than required, and this is calculated in different ways in differents part of the code for example. For circles wallet creation, the code fails in this line 
During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 451, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 734, in __protected_call__
    return self.run(*args, **kwargs)
  File "/safe-relay-service/safe_relay_service/relay/tasks.py", line 688, in circles_onboarding_safe_task
    FundingServiceProvider().send_eth_to(
  File "/safe-relay-service/safe_relay_service/relay/services/funding_service.py", line 83, in send_eth_to
    return self.ethereum_client.send_eth_to(
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1950, in send_eth_to
    return self.send_unsigned_transaction(
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1868, in send_unsigned_transaction
    return self.send_raw_transaction(signed_tx.rawTransaction)
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 141, in with_exception_handling
    raise exc
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 135, in with_exception_handling
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1817, in send_raw_transaction
```
In `send_eth_to` we dont pass the paremeter gasprice and this gets calculated in             gas_price = self.gas_station.get_gas_prices().standard. I debugged this functions and works fine when I pass the latest blocks, commenting this https://github.com/CirclesUBI/safe-relay-service/blob/main/safe_relay_service/relay/services/funding_service.py#L69
The problem seems to be that it keeps getting the values from the cache, that's why always we have this printed on the logs 
`Starting Gas Price Calculation
2022-12-13 15:35:45,013 [INFO] [280d881d/calculate_gas_prices] 2022-12-13 15:35:45.013827+00:00 lowest=1000000000 safe_low=1000000000 standard=1000000000 fast=1000000000 fastest=1000000000`

so the solution is to delete the cache and make the relayer recalculate the price

**Comment by JacqueGM** [comment]
As pointed out above, the main problem for transaction to fail with the `FeeTooLow` Error is the gas_price calculation. The GasStation service keeps returning forever for all the values of gas 10000000, even though each block might have a different value so this should change. I have being trying to change it but I did not manage to change it as I wanted, so for now for transactions to work I have hardcoded the BaseFee value which was missing from the gas_price calculation, whenever this has an impact as can see in this PR https://github.com/CirclesUBI/safe-relay-service/pull/69

**Comment by JacqueGM** [comment]
The problem with the fix price came from a configuration issue, under config/setting/production  - this was set to 1, ergo the value was always the same. This PR https://github.com/CirclesUBI/safe-relay-service/pull/70 should fix the issue. For now, I can see that the FeeTooLow error is thrown when trying to send to unverified account so this is an acceptable behaivour. We will keep monitoring this but for now no other FeeTooLow errors have appeared.
