### ISSUE TITLE
Trust limit exceeded Exception in Toke test of the core

### ISSUE THREAD

**Issue by llunaCreixent** [CirclesUBI/safe-relay-service#66]
We need to debug and check if this exception should be propagated.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 711, in estimate_tx_gas_with_web3
    return self.ethereum_client.estimate_gas(
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1607, in estimate_gas
    return self.w3.eth.estimate_gas(tx, block_identifier=block_identifier)
  File "/usr/local/lib/python3.9/site-packages/web3/eth.py", line 868, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "/usr/local/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 561, in raise_solidity_error_on_revert
    raise ContractLogicError(f'execution reverted: {response["error"]["message"]}')
web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert Trust limit exceeded

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/safe-relay-service/safe_relay_service/relay/views_v2.py", line 164, in post
    transaction_estimation = TransactionServiceProvider().estimate_tx(
  File "/safe-relay-service/safe_relay_service/relay/services/transaction_service.py", line 285, in estimate_tx
    safe_tx_gas = safe.estimate_tx_gas(to, value, data, operation)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 803, in estimate_tx_gas
    self.estimate_tx_gas_with_web3(to, value, data)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 715, in estimate_tx_gas_with_web3
    raise CannotEstimateGas(
gnosis.safe.exceptions.CannotEstimateGas: Cannot estimate gas with `eth_estimateGas`: execution reverted: VM Exception while processing transaction: revert Trust limit exceeded
```

**Comment by llunaCreixent** [comment]
Another exception in the tests (lib. user, or utils):
```
2022-11-29 15:34:18,889 [WARNING] [MainProcess] http://relay.circles.local/api/v2/safes/0xc4F4cEbB73C3366606c87f6186443dA8370fFBee/transactions/estimate/ - Exception: CannotEstimateGas: Cannot estimate gas with `eth_estimateGas`: execution reverted: VM Exception while processing transaction: revert GS202 - Data received {'safe': '0xc4F4cEbB73C3366606c87f6186443dA8370fFBee', 'data': '0x0d582f1300000000000000000000000022d491bde2303f2f43325b2108d26f1eaba1e32b0000000000000000000000000000000000000000000000000000000000000000', 'to': '0xc4F4cEbB73C3366606c87f6186443dA8370fFBee', 'value': 0, 'operation': 0, 'gas_token': '0x0000000000000000000000000000000000000000'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 798, in estimate_tx_gas
    self.estimate_tx_gas_by_trying(to, value, data, operation)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 739, in estimate_tx_gas_by_trying
    gas_estimated = self.estimate_tx_gas_with_safe(to, value, data, operation)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 695, in estimate_tx_gas_with_safe
    return parse_revert_data(
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 652, in parse_revert_data
    raise CannotEstimateGas("Received %s for tx=%s" % (result.hex(), tx))
gnosis.safe.exceptions.CannotEstimateGas: Received 0x for tx={'value': 0, 'chainId': 1337, 'from': '0xc4F4cEbB73C3366606c87f6186443dA8370fFBee', 'gas': 0, 'gasPrice': 0, 'to': '0xc4F4cEbB73C3366606c87f6186443dA8370fFBee', 'data': '0xc4ca3a9c000000000000000000000000c4f4cebb73c3366606c87f6186443da8370ffbee00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000440d582f1300000000000000000000000022d491bde2303f2f43325b2108d26f1eaba1e32b000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 711, in estimate_tx_gas_with_web3
    return self.ethereum_client.estimate_gas(
  File "/usr/local/lib/python3.9/site-packages/gnosis/eth/ethereum_client.py", line 1607, in estimate_gas
    return self.w3.eth.estimate_gas(tx, block_identifier=block_identifier)
  File "/usr/local/lib/python3.9/site-packages/web3/eth.py", line 868, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/usr/local/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/usr/local/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 666, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 641, in cytoolz.functoolz.c_pipe
  File "/usr/local/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 561, in raise_solidity_error_on_revert
    raise ContractLogicError(f'execution reverted: {response["error"]["message"]}')
web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: revert GS202

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/safe-relay-service/safe_relay_service/relay/views_v2.py", line 164, in post
    transaction_estimation = TransactionServiceProvider().estimate_tx(
  File "/safe-relay-service/safe_relay_service/relay/services/transaction_service.py", line 285, in estimate_tx
    safe_tx_gas = safe.estimate_tx_gas(to, value, data, operation)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 803, in estimate_tx_gas
    self.estimate_tx_gas_with_web3(to, value, data)
  File "/usr/local/lib/python3.9/site-packages/gnosis/safe/safe.py", line 715, in estimate_tx_gas_with_web3
    raise CannotEstimateGas(
gnosis.safe.exceptions.CannotEstimateGas: Cannot estimate gas with `eth_estimateGas`: execution reverted: VM Exception while processing transaction: revert GS202
```

**Comment by louilinn** [comment]
Is this related to the issue with the pathfinder exceeding trust / send limits?
